### PR TITLE
Add Register Devices endpoints

### PR DESCRIPTION
**Pull request by BalestraPatrick**
Hey! Me again with a small PR to add support for a new endpoint. I also updated the changelog and bumped the version so that it's easier for you to release a new version. 
Let me know if that's fine 😄

### CODE REVIEW

**Comment by ppawlak** [comment]
Hey @BalestraPatrick, thanks for this new contribution!
May I ask you a small change: can you make the new version number 0.7.0? 
I'd like to increment the "second" number as soon as there is a new feature.

**Comment by BalestraPatrick** [comment]
@ppawlak Done!

**Comment by BalestraPatrick** [comment]
@ppawlak Anything left to merge and make a new release with this change? 😄

**Comment by ppawlak** [comment]
> @ppawlak Anything left to merge and make a new release with this change? 😄

Time 😉 
I'll do it soon.

**Comment by ppawlak** [comment]
Version 0.7.0 is on PyPI

**Pull request merged**
