### PR TITLE
Passing the key file as string value

### PR DESCRIPTION
**Pull request by kpotehin**
Hey! I've just made a small change so we can pass the key directly, not using the file. It'll make using the library much easier in cases when you store the key in DB, secrets on environment variables.

Hope you'll find it useful and thanks a lot for your work!

### CODE REVIEW

**Comment by kpotehin** [comment]
Also you've broken the report methods by adding required `sort` argument to `_build_query_parameters ` function, I've made it optional.

**Comment by ppawlak** [comment]
This is indeed a good addition!
I will have a look and merge it soon.

Thanks! (and thanks for the fix)

**Comment by kpotehin** [comment]
Great! When do you plan to publish the new version?

**Comment by ppawlak** [comment]
> Great! When do you plan to publish the new version?

Done!
https://pypi.org/project/appstoreconnect/0.4.1/

**Pull request merged**
